### ISSUE TITLE
 Get post info 

### ISSUE THREAD

**Issue by 89z** [OnFireMohamed/InstagramMediaDownloader#2]
If I have a post such as this:

https://www.instagram.com/p/CT-cnxGhvvO/

How do I get the info for this post? Sorry for the basic question, but I have looked over the API and am not seeing a way to do this.

**Comment by majhcc** [comment]
You can get post info by adding ` /?__a=1` like this https://www.instagram.com/p/CT72FMwjX7S/?__a=1
Mybe you need to login to get information
